/* 리눅스마스터 2급 1차 — 실전 모의고사 (50문항 · 60분 · 100점)
   과목 배분: 1과목 리눅스 일반 35문항 · 2과목 리눅스 활용 15문항
   ─ KAIT 공개 출제기준의 대분류(리눅스 일반 / 리눅스 활용)를 따르며, 과목별 문항 수는
     실제 출제 비중에 맞춰 배분한 것입니다. 1차 시험은 총점 60점 이상이면 합격이고 과락은 없습니다.
   엔진(assets/exam-engine.js)이 window.EXAMS 로 읽습니다. */
window.EXAMS = [];
const EXAMS = window.EXAMS;

EXAMS.push({title:"제1회 실전 모의고사",note:"명령어·권한·프로세스 중심 · 표준 난이도",q:[

/* ---------------- 1과목 · 리눅스 일반 ---------------- */
{n:1,s:1,q:"1991년 리눅스 커널을 처음 개발하여 공개한 인물은?",o:["리처드 스톨만","리누스 토발즈","켄 톰슨","앤드루 타넨바움"],a:1,e:"핀란드 헬싱키 대학의 리누스 토발즈가 미닉스(MINIX)에 영향을 받아 개발했습니다. 리처드 스톨만은 GNU 프로젝트와 FSF의 창시자입니다."},
{n:2,s:1,q:"GPL(GNU General Public License)의 특징으로 옳지 않은 것은?",o:["소스 코드를 자유롭게 열람하고 수정할 수 있다","수정한 프로그램을 배포할 때 동일한 라이선스를 적용해야 한다","프로그램을 판매하여 수익을 얻을 수 없다","누구나 자유롭게 복제하고 배포할 수 있다"],a:2,e:"GPL은 판매 자체를 금지하지 않습니다. 다만 배포 시 소스 코드를 함께 제공하고 동일한 GPL을 적용해야 합니다(카피레프트)."},
{n:3,s:1,q:"레드햇 계열 배포판에 해당하지 않는 것은?",o:["CentOS","Fedora","Rocky Linux","Ubuntu"],a:3,e:"Ubuntu는 데비안 계열입니다. 레드햇 계열은 RHEL, CentOS, Fedora, Rocky Linux 등이며 rpm 패키지를 사용합니다."},
{n:4,s:1,q:"리눅스 부팅 시 커널을 메모리에 적재하는 부트로더는?",o:["GRUB","init","systemd","BIOS"],a:0,e:"GRUB(GRand Unified Bootloader)은 커널을 선택해 메모리에 올립니다. systemd는 커널이 올라간 뒤 실행되는 최초의 프로세스입니다."},
{n:5,s:1,q:"systemd 환경에서 다중 사용자 CLI 모드에 해당하는 target은?",o:["graphical.target","multi-user.target","rescue.target","emergency.target"],a:1,e:"multi-user.target은 기존 런레벨 3에 해당하고, graphical.target은 런레벨 5에 해당합니다."},
{n:6,s:1,q:"리눅스에서 기본으로 사용하는 저널링 파일 시스템이 아닌 것은?",o:["ext4","XFS","Btrfs","FAT32"],a:3,e:"FAT32는 저널링을 지원하지 않는 윈도우 계열 파일 시스템입니다."},
{n:7,s:1,q:"물리 메모리가 부족할 때 디스크의 일부를 메모리처럼 사용하는 영역은?",o:["스왑(swap) 영역","부트 파티션","루트 파티션","캐시 영역"],a:0,e:"스왑 영역은 가상 메모리로 활용되며, free 명령으로 사용량을 확인할 수 있습니다."},
{n:8,s:1,q:"시스템 설정 파일들이 위치하는 디렉터리는?",o:["/etc","/var","/usr","/dev"],a:0,e:"/etc는 설정 파일, /var는 로그처럼 자주 변하는 데이터, /usr는 응용 프로그램, /dev는 장치 파일이 있는 디렉터리입니다."},
{n:9,s:1,q:"로그 파일이 주로 저장되는 디렉터리는?",o:["/etc/log","/var/log","/usr/log","/tmp/log"],a:1,e:"/var/log 아래에 messages, secure, boot.log 등 시스템 로그가 쌓입니다."},
{n:10,s:1,q:"현재 작업 중인 디렉터리의 경로를 출력하는 명령어는?",o:["pwd","cd","ls","dir"],a:0,e:"pwd(print working directory)입니다."},
{n:11,s:1,q:"숨김 파일을 포함해 디렉터리의 모든 파일을 자세히 출력하는 명령은?",o:["ls -l","ls -a","ls -al","ls -R"],a:2,e:"-a는 숨김 파일 포함, -l은 상세 정보 출력이므로 두 옵션을 함께 씁니다."},
{n:12,s:1,q:"파일 권한이 'rwxr-x---' 일 때 8진수 표기로 옳은 것은?",o:["740","750","755","770"],a:1,e:"rwx=7, r-x=5, ---=0 이므로 750입니다."},
{n:13,s:1,q:"file.txt에 대해 그룹 사용자에게만 쓰기 권한을 추가하는 명령은?",o:["chmod g+w file.txt","chmod o+w file.txt","chmod u+w file.txt","chmod a+w file.txt"],a:0,e:"u는 소유자, g는 그룹, o는 기타 사용자, a는 전체입니다."},
{n:14,s:1,q:"umask 값이 022일 때 새로 생성되는 일반 파일의 기본 권한은?",o:["644","755","666","777"],a:0,e:"일반 파일의 기본값 666에서 022를 빼면 644입니다. 디렉터리는 777에서 빼서 755가 됩니다."},
{n:15,s:1,q:"파일의 소유 그룹만 변경하는 명령어는?",o:["chmod","chown","chgrp","chattr"],a:2,e:"chgrp는 그룹만, chown은 소유자(및 그룹)를, chmod는 권한을 변경합니다."},
{n:16,s:1,q:"디렉터리에 설정하면 소유자만 자신의 파일을 삭제할 수 있게 하는 특수 권한은?",o:["SetUID","SetGID","Sticky Bit","umask"],a:2,e:"/tmp에 설정된 Sticky Bit가 대표적이며, 권한 표시에서 t로 나타납니다."},
{n:17,s:1,q:"심볼릭 링크에 대한 설명으로 옳은 것은?",o:["원본 파일과 동일한 inode 번호를 갖는다","원본을 삭제해도 링크는 정상 동작한다","서로 다른 파일 시스템 사이에도 만들 수 있다","디렉터리에는 만들 수 없다"],a:2,e:"심볼릭 링크(ln -s)는 경로를 가리키는 별도 파일이라 파일 시스템을 넘나들 수 있고 디렉터리에도 만들 수 있습니다. 원본을 지우면 깨집니다. 하드 링크가 inode를 공유합니다."},
{n:18,s:1,q:"현재 디렉터리 아래에서 이름이 'test'로 시작하는 파일을 찾는 명령은?",o:["find . -name 'test*'","grep -r 'test*' .","locate test","which test"],a:0,e:"find는 파일 자체를 조건으로 찾고, grep은 파일 내용에서 문자열을 찾습니다."},
{n:19,s:1,q:"파일 내용 중 'error'라는 문자열이 포함된 줄만 출력하는 명령은?",o:["cat error file.log","grep error file.log","find error file.log","sed error file.log"],a:1,e:"grep 패턴 파일명 형식으로 사용하며, -i는 대소문자 무시, -v는 반전, -n은 줄 번호 출력입니다."},
{n:20,s:1,q:"명령의 실행 결과를 기존 파일 뒤에 덧붙여 저장하는 리다이렉션 기호는?",o:[">","<",">>","|"],a:2,e:"> 는 덮어쓰기, >> 는 이어쓰기, < 는 입력 리다이렉션, | 는 파이프입니다."},
{n:21,s:1,q:"실행 중인 프로세스를 CPU 사용률 순으로 실시간 확인하는 명령은?",o:["ps","top","jobs","nice"],a:1,e:"top(또는 htop)은 주기적으로 갱신되며, ps는 특정 시점의 상태를 한 번 출력합니다."},
{n:22,s:1,q:"프로세스를 강제로 즉시 종료할 때 사용하는 시그널 번호는?",o:["1","9","15","18"],a:1,e:"SIGKILL(9)은 무조건 종료, SIGTERM(15)은 정상 종료 요청, SIGHUP(1)은 재시작 또는 설정 재적용에 사용됩니다."},
{n:23,s:1,q:"백그라운드로 실행 중인 작업을 포그라운드로 전환하는 명령은?",o:["bg","fg","jobs","nohup"],a:1,e:"jobs로 작업 번호를 확인한 뒤 fg %1 처럼 사용합니다. 명령 뒤에 &를 붙이면 백그라운드로 실행됩니다."},
{n:24,s:1,q:"지정한 시각에 작업을 주기적으로 반복 실행하도록 등록하는 것은?",o:["at","cron","batch","nohup"],a:1,e:"cron은 반복 실행(crontab -e), at은 1회성 예약 실행입니다."},
{n:25,s:1,q:"crontab 항목 '30 2 * * 1 /backup.sh' 의 실행 시점으로 옳은 것은?",o:["매일 오전 2시 30분","매주 월요일 오전 2시 30분","매월 1일 오전 2시 30분","매주 일요일 오전 2시 30분"],a:1,e:"필드 순서는 분 시 일 월 요일이며, 요일 1은 월요일입니다."},
{n:26,s:1,q:"대부분의 리눅스 배포판에서 기본 셸로 사용하는 것은?",o:["sh","bash","csh","ksh"],a:1,e:"bash(Bourne Again SHell)가 기본이며, 사용자의 기본 셸은 /etc/passwd 마지막 필드에 기록됩니다."},
{n:27,s:1,q:"명령어를 찾을 경로 목록이 저장된 환경 변수는?",o:["HOME","PATH","SHELL","PWD"],a:1,e:"echo $PATH로 확인하며, 콜론(:)으로 구분된 디렉터리에서 실행 파일을 찾습니다."},
{n:28,s:1,q:"자주 쓰는 명령에 짧은 별칭을 지정하는 명령어는?",o:["alias","export","set","env"],a:0,e:"alias ll='ls -al' 형태로 지정하며, 해제는 unalias입니다."},
{n:29,s:1,q:"/etc/passwd 파일의 필드 구성 순서로 옳은 것은?",o:["사용자명:암호:UID:GID:설명:홈디렉터리:셸","사용자명:UID:GID:암호:셸:홈디렉터리:설명","UID:사용자명:GID:암호:홈디렉터리:설명:셸","사용자명:암호:GID:UID:홈디렉터리:셸:설명"],a:0,e:"7개 필드가 콜론으로 구분되며, 암호 필드는 x로 표시되고 실제 암호는 /etc/shadow에 저장됩니다."},
{n:30,s:1,q:"암호화된 사용자 비밀번호와 계정 만료 정보가 저장되는 파일은?",o:["/etc/passwd","/etc/shadow","/etc/group","/etc/login.defs"],a:1,e:"/etc/shadow는 root만 읽을 수 있도록 권한이 제한되어 있습니다."},
{n:31,s:1,q:"기존 사용자 계정의 속성을 변경하는 명령어는?",o:["useradd","usermod","userdel","chage"],a:1,e:"usermod -aG 그룹명 사용자 처럼 사용합니다. chage는 암호 만료 정책만 다룹니다."},
{n:32,s:1,q:"데비안 계열에서 패키지를 설치하는 명령으로 알맞은 것은?",o:["yum install nginx","dnf install nginx","apt install nginx","rpm -ivh nginx"],a:2,e:"데비안·우분투는 apt/dpkg, 레드햇 계열은 yum/dnf/rpm을 사용합니다."},
{n:33,s:1,q:"디렉터리를 tar로 묶으면서 gzip으로 압축하는 명령은?",o:["tar -cvf data.tar data/","tar -zcvf data.tar.gz data/","tar -xvf data.tar","tar -zxvf data.tar.gz"],a:1,e:"c는 생성, x는 해제, z는 gzip, v는 과정 출력, f는 파일명 지정입니다."},
{n:34,s:1,q:"파일 시스템별 디스크 사용량과 남은 용량을 확인하는 명령은?",o:["df -h","du -sh","free -h","fdisk -l"],a:0,e:"df는 파일 시스템 단위, du는 디렉터리·파일 단위 사용량, free는 메모리 사용량을 봅니다."},
{n:35,s:1,q:"부팅 시 자동으로 마운트할 파일 시스템을 정의하는 설정 파일은?",o:["/etc/fstab","/etc/mtab","/etc/inittab","/etc/exports"],a:0,e:"/etc/fstab에 장치, 마운트 지점, 파일 시스템 종류, 옵션, 덤프·검사 순서를 기술합니다."},

/* ---------------- 2과목 · 리눅스 활용 ---------------- */
{n:36,s:2,q:"X 윈도 시스템의 구조에 대한 설명으로 옳은 것은?",o:["X 서버는 사용자의 응용 프로그램을 의미한다","X 클라이언트가 키보드·마우스 등 입출력 장치를 관리한다","X 서버가 입출력 장치를 관리하고 화면에 출력한다","X 윈도는 네트워크를 통한 원격 표시를 지원하지 않는다"],a:2,e:"X는 서버·클라이언트 구조이며, 사용자가 앉아 있는 쪽이 X 서버(장치·화면 담당), 프로그램 쪽이 X 클라이언트입니다. 네트워크 투명성을 지원합니다."},
{n:37,s:2,q:"리눅스의 대표적인 데스크톱 환경(Desktop Environment)이 아닌 것은?",o:["GNOME","KDE","XFCE","Xorg"],a:3,e:"Xorg는 X 윈도 시스템의 구현체(서버)이지 데스크톱 환경이 아닙니다."},
{n:38,s:2,q:"그래픽 로그인 화면을 제공하는 디스플레이 매니저에 해당하지 않는 것은?",o:["gdm","kdm","lightdm","xdg"],a:3,e:"gdm(GNOME), kdm(KDE), lightdm, sddm 등이 디스플레이 매니저입니다."},
{n:39,s:2,q:"X 클라이언트 프로그램의 출력을 보낼 화면을 지정하는 환경 변수는?",o:["TERM","DISPLAY","XAUTHORITY","PATH"],a:1,e:"export DISPLAY=192.168.0.5:0.0 처럼 지정하면 원격 X 서버로 화면을 보낼 수 있습니다."},
{n:40,s:2,q:"DNS 서버 주소를 지정하는 설정 파일은?",o:["/etc/hosts","/etc/resolv.conf","/etc/services","/etc/networks"],a:1,e:"/etc/resolv.conf에 nameserver 항목을 기록합니다. /etc/hosts는 이름과 IP를 수동 매핑합니다."},
{n:41,s:2,q:"ifconfig를 대체하여 네트워크 인터페이스와 주소를 관리하는 최신 명령은?",o:["ip","netstat","route","arp"],a:0,e:"ip addr, ip link, ip route 형태로 사용하며 iproute2 패키지에 포함되어 있습니다."},
{n:42,s:2,q:"현재 열려 있는 소켓과 리스닝 포트를 확인하는 명령으로 옳은 것은?",o:["ss -tuln","df -h","du -sh","top -b"],a:0,e:"ss(또는 netstat) -t TCP, -u UDP, -l 리스닝, -n 숫자 표기 옵션입니다."},
{n:43,s:2,q:"목적지까지의 네트워크 경로를 홉 단위로 추적하는 명령은?",o:["ping","traceroute","nslookup","hostname"],a:1,e:"traceroute(윈도우는 tracert)는 TTL을 늘려 가며 각 라우터의 응답을 받아 경로를 표시합니다."},
{n:44,s:2,q:"리눅스에서 사용하는 대표적인 웹 서버 소프트웨어의 조합으로 옳은 것은?",o:["Apache, Nginx","Postfix, Sendmail","Samba, NFS","Bind, Dnsmasq"],a:0,e:"Postfix·Sendmail은 메일, Samba·NFS는 파일 공유, Bind는 DNS 서버입니다."},
{n:45,s:2,q:"SSH 프로토콜 위에서 안전하게 파일을 전송하는 방식은?",o:["FTP","TFTP","SFTP","NFS"],a:2,e:"SFTP와 SCP는 22번 포트의 SSH를 이용해 암호화 전송을 합니다. FTP는 평문으로 전송됩니다."},
{n:46,s:2,q:"리눅스에서 윈도우 클라이언트와 파일·프린터를 공유하기 위해 사용하는 서비스는?",o:["Samba","NFS","Bind","vsftpd"],a:0,e:"Samba는 SMB/CIFS 프로토콜을 구현하여 윈도우 네트워크 공유에 참여합니다."},
{n:47,s:2,q:"유닉스·리눅스 시스템 사이에서 원격 디렉터리를 마운트해 사용하는 서비스는?",o:["Samba","NFS","SSH","DHCP"],a:1,e:"NFS(Network File System)는 /etc/exports에 공유 대상을 정의합니다."},
{n:48,s:2,q:"리눅스에서 사용하는 메일 전송 에이전트(MTA)에 해당하는 것은?",o:["Postfix","Dovecot","Squid","Nagios"],a:0,e:"Postfix·Sendmail은 메일을 보내는 MTA, Dovecot은 POP3·IMAP을 제공하는 MDA입니다. Squid는 프록시, Nagios는 모니터링 도구입니다."},
{n:49,s:2,q:"컨테이너 기술에 대한 설명으로 옳은 것은?",o:["게스트 OS 전체를 가상화하여 실행한다","호스트 커널을 공유하므로 가볍고 시작이 빠르다","하이퍼바이저가 반드시 필요하다","리눅스에서는 사용할 수 없다"],a:1,e:"도커 같은 컨테이너는 OS 수준 가상화로 호스트 커널을 공유합니다. 게스트 OS를 통째로 올리는 것은 가상 머신 방식입니다."},
{n:50,s:2,q:"리눅스 커널을 기반으로 만들어진 모바일 운영체제는?",o:["iOS","Android","Windows Phone","BlackBerry OS"],a:1,e:"안드로이드는 리눅스 커널 위에 자체 런타임(ART)과 프레임워크를 올린 구조입니다. iOS는 Darwin(BSD 계열) 기반입니다."}
]});

EXAMS.push({title:"제2회 실전 모의고사",note:"부팅·파일시스템·셸 스크립트 · 심화",q:[

/* ---------------- 1과목 · 리눅스 일반 ---------------- */
{n:1,s:1,q:"리눅스 시스템의 부팅 순서로 옳은 것은?",o:["BIOS/UEFI → 부트로더 → 커널 → init/systemd","부트로더 → BIOS/UEFI → 커널 → init/systemd","커널 → BIOS/UEFI → 부트로더 → init/systemd","BIOS/UEFI → 커널 → 부트로더 → init/systemd"],a:0,e:"전원이 들어오면 펌웨어가 POST를 수행하고 부트로더(GRUB)를 읽어 커널을 적재한 뒤, 커널이 최초 프로세스인 systemd(PID 1)를 실행합니다."},
{n:2,s:1,q:"현재 시스템에 적재된 커널 모듈 목록을 확인하는 명령어는?",o:["lsmod","modprobe","insmod","depmod"],a:0,e:"lsmod로 조회하고, modprobe는 의존성을 함께 처리해 적재·제거하며, rmmod는 제거합니다."},
{n:3,s:1,q:"의존성까지 자동으로 처리하며 커널 모듈을 적재하는 명령어는?",o:["insmod","modprobe","lsmod","rmmod"],a:1,e:"insmod는 지정한 모듈만 그대로 올리지만, modprobe는 필요한 의존 모듈까지 함께 적재합니다."},
{n:4,s:1,q:"systemd 환경에서 기본으로 부팅될 target을 확인하는 명령은?",o:["systemctl get-default","runlevel","who -r","systemctl list-units"],a:0,e:"변경은 systemctl set-default multi-user.target 형태로 합니다."},
{n:5,s:1,q:"파티션에 ext4 파일 시스템을 생성하는 명령은?",o:["fdisk /dev/sdb1","mkfs.ext4 /dev/sdb1","mount /dev/sdb1 /data","fsck /dev/sdb1"],a:1,e:"fdisk는 파티션을 나누고, mkfs는 파일 시스템을 만들며, mount는 연결, fsck는 검사·복구를 담당합니다."},
{n:6,s:1,q:"파일 시스템의 무결성을 검사하고 복구하는 명령어는?",o:["fsck","mkfs","du","df"],a:0,e:"fsck는 마운트를 해제한 상태에서 수행해야 안전합니다."},
{n:7,s:1,q:"LVM 구성 요소의 계층 순서로 옳은 것은?",o:["PV → VG → LV","LV → VG → PV","VG → PV → LV","PV → LV → VG"],a:0,e:"물리 볼륨(PV)을 모아 볼륨 그룹(VG)을 만들고, 그 안에서 논리 볼륨(LV)을 잘라 사용합니다. 온라인 확장이 가능한 것이 장점입니다."},
{n:8,s:1,q:"파일의 메타데이터(소유자, 권한, 크기, 블록 위치)를 담고 있는 자료구조는?",o:["inode","슈퍼블록","데이터 블록","디렉터리 엔트리"],a:0,e:"파일 이름은 inode가 아니라 디렉터리 엔트리에 저장되며, 이름과 inode 번호가 연결됩니다."},
{n:9,s:1,q:"하드 링크에 대한 설명으로 옳은 것은?",o:["원본과 동일한 inode를 공유하며 원본을 지워도 데이터에 접근할 수 있다","다른 파일 시스템에도 만들 수 있다","디렉터리에 자유롭게 만들 수 있다","원본을 삭제하면 즉시 깨진다"],a:0,e:"하드 링크는 inode를 공유하므로 링크 수가 0이 될 때까지 데이터가 유지됩니다. 파일 시스템을 넘을 수 없고 일반 사용자는 디렉터리에 만들 수 없습니다."},
{n:10,s:1,q:"SetUID 권한을 8진수로 표기할 때 사용하는 값은?",o:["1000","2000","4000","7000"],a:2,e:"SetUID는 4000, SetGID는 2000, Sticky Bit는 1000입니다. chmod 4755 file 처럼 사용합니다."},
{n:11,s:1,q:"파일 하나에 사용자별로 세밀한 권한을 추가로 부여할 때 사용하는 명령은?",o:["setfacl","chmod","umask","chattr"],a:0,e:"setfacl -m u:kim:rw file 처럼 지정하고 getfacl로 확인합니다. 기본 소유자·그룹·기타 3분류로 부족할 때 씁니다."},
{n:12,s:1,q:"파일을 삭제나 변경이 불가능하도록 속성을 설정하는 명령어는?",o:["chattr +i","chmod 000","chown root","umask 777"],a:0,e:"chattr +i(immutable)를 걸면 root라도 수정·삭제할 수 없으며 lsattr로 확인합니다."},
{n:13,s:1,q:"'su -' 와 'su' 의 차이로 옳은 것은?",o:["'su -'는 대상 사용자의 환경 변수와 홈 디렉터리까지 적용한다","'su'는 비밀번호를 묻지 않는다","'su -'는 root로만 전환할 수 있다","두 명령은 완전히 동일하다"],a:0,e:"하이픈을 붙이면 로그인 셸로 전환되어 대상 사용자의 프로파일이 다시 읽힙니다."},
{n:14,s:1,q:"/etc/group 파일의 필드 구성으로 옳은 것은?",o:["그룹명:암호:GID:그룹 구성원","그룹명:GID:암호:구성원","GID:그룹명:구성원:암호","그룹명:구성원:GID:암호"],a:0,e:"네 개의 필드가 콜론으로 구분되며, 마지막 필드에 보조 그룹 구성원이 쉼표로 나열됩니다."},
{n:15,s:1,q:"사용자 계정의 암호 만료일과 변경 주기를 설정하는 명령어는?",o:["chage","passwd","usermod","chsh"],a:0,e:"chage -M 90 user 처럼 최대 사용 일수를 지정합니다. chsh는 로그인 셸을 변경합니다."},
{n:16,s:1,q:"프로세스의 우선순위를 조정할 때 사용하는 nice 값의 범위와 의미로 옳은 것은?",o:["-20 ~ 19이며 값이 작을수록 우선순위가 높다","0 ~ 100이며 값이 클수록 우선순위가 높다","-20 ~ 19이며 값이 클수록 우선순위가 높다","1 ~ 10이며 값이 작을수록 우선순위가 낮다"],a:0,e:"nice로 실행 시 지정하고, 이미 실행 중인 프로세스는 renice로 조정합니다. 우선순위를 높이는 것(음수)은 root만 가능합니다."},
{n:17,s:1,q:"부모 프로세스가 종료 상태를 회수하지 않아 프로세스 테이블에만 남아 있는 프로세스는?",o:["좀비(Zombie) 프로세스","고아(Orphan) 프로세스","데몬(Daemon) 프로세스","백그라운드 프로세스"],a:0,e:"부모가 먼저 죽어 init/systemd에 입양되는 것은 고아 프로세스입니다."},
{n:18,s:1,q:"systemd에서 서비스의 현재 상태를 확인하는 명령은?",o:["systemctl status sshd","service sshd restart","chkconfig sshd on","init 3"],a:0,e:"start/stop/restart/status/enable/disable 형태로 사용합니다."},
{n:19,s:1,q:"systemd 저널에 기록된 로그를 조회하는 명령어는?",o:["journalctl","dmesg","logrotate","last"],a:0,e:"journalctl -u sshd -f 처럼 서비스 단위로 실시간 조회할 수 있습니다. dmesg는 커널 링 버퍼를 봅니다."},
{n:20,s:1,q:"로그 파일이 무한정 커지지 않도록 주기적으로 분할·압축·삭제하는 도구는?",o:["logrotate","rsyslog","journalctl","cron"],a:0,e:"/etc/logrotate.conf와 /etc/logrotate.d/ 아래 설정을 두고 cron이 주기적으로 실행합니다."},
{n:21,s:1,q:"디스크나 파티션을 블록 단위로 그대로 복사할 때 사용하는 명령어는?",o:["dd","cp","tar","rsync"],a:0,e:"dd if=/dev/sda of=/dev/sdb bs=4M 형태로 사용합니다. 대상 지정을 잘못하면 데이터가 사라지므로 주의해야 합니다."},
{n:22,s:1,q:"변경된 부분만 전송하여 효율적으로 동기화·백업하는 명령어는?",o:["rsync","scp","dd","cpio"],a:0,e:"rsync -avz src/ user@host:/dest/ 형태로 원격 동기화도 가능합니다."},
{n:23,s:1,q:"crontab에서 시스템이 부팅될 때 한 번 실행하도록 지정하는 특수 문자열은?",o:["@reboot","@daily","@hourly","@yearly"],a:0,e:"@reboot 외에 @daily, @weekly, @monthly, @yearly 같은 축약 표현을 사용할 수 있습니다."},
{n:24,s:1,q:"셸 스크립트에서 첫 줄에 인터프리터를 지정하는 표기는?",o:["#!/bin/bash","#/bin/bash","!/bin/bash","//bin/bash"],a:0,e:"셔뱅(shebang)이라 하며, 스크립트를 실행할 인터프리터 경로를 지정합니다."},
{n:25,s:1,q:"셸 스크립트에서 첫 번째 인자를 참조하는 변수는?",o:["$0","$1","$#","$@"],a:1,e:"$0은 스크립트 이름, $1~$9는 인자, $#은 인자 개수, $@는 전체 인자, $?는 직전 명령의 종료 상태입니다."},
{n:26,s:1,q:"직전에 실행한 명령의 종료 상태(성공 여부)를 담고 있는 특수 변수는?",o:["$!","$?","$$","$_"],a:1,e:"$?가 0이면 정상 종료, 0이 아니면 오류입니다. $$는 현재 셸의 PID입니다."},
{n:27,s:1,q:"셸 스크립트에서 파일이 존재하는지 검사하는 조건식은?",o:["[ -f file ]","[ -x file ]","[ -z file ]","[ -n file ]"],a:0,e:"-f는 일반 파일 존재, -d는 디렉터리, -e는 존재 여부, -x는 실행 권한, -z는 문자열 길이 0을 검사합니다."},
{n:28,s:1,q:"로그인 시 한 번만 읽히며 사용자별 환경 변수를 설정하기에 적합한 파일은?",o:["~/.bash_profile","~/.bashrc","/etc/hosts","~/.bash_history"],a:0,e:".bash_profile은 로그인 셸에서 한 번, .bashrc는 새 셸이 열릴 때마다 읽힙니다. alias는 주로 .bashrc에 둡니다."},
{n:29,s:1,q:"표준 출력과 표준 에러를 함께 파일로 저장하는 표기로 옳은 것은?",o:["cmd > out.log 2>&1","cmd 2>&1 > out.log","cmd > out.log &2>1","cmd >> out.log 1>&2"],a:0,e:"먼저 표준 출력을 파일로 돌린 뒤 표준 에러를 표준 출력으로 합쳐야 합니다. 순서를 바꾸면 에러는 화면에 남습니다."},
{n:30,s:1,q:"앞 명령의 출력을 뒤 명령의 인자로 전달할 때 사용하는 명령어는?",o:["xargs","tee","nohup","exec"],a:0,e:"find . -name '*.log' | xargs rm 처럼 사용합니다. tee는 출력을 화면과 파일에 동시에 보냅니다."},
{n:31,s:1,q:"파일에서 'old'를 'new'로 모두 바꿔 출력하는 명령은?",o:["sed 's/old/new/g' file","awk '{print $1}' file","grep old file","sort file"],a:0,e:"sed는 스트림 편집기이며 g 플래그를 붙여야 줄마다 전체를 치환합니다. -i 옵션은 파일을 직접 수정합니다."},
{n:32,s:1,q:"공백으로 구분된 세 번째 필드만 출력하는 명령은?",o:["awk '{print $3}' file","sed -n '3p' file","cut -c3 file","head -3 file"],a:0,e:"awk는 필드 단위 처리에 강하며, sed -n '3p'는 세 번째 줄을 출력합니다."},
{n:33,s:1,q:"정렬한 뒤 중복을 제거하고 각 항목의 개수를 세는 명령 조합은?",o:["sort file | uniq -c","uniq file | sort -c","cat file | wc -l","grep -c file"],a:0,e:"uniq는 인접한 중복만 처리하므로 반드시 sort를 먼저 해야 합니다."},
{n:34,s:1,q:"파일의 줄 수를 세는 명령은?",o:["wc -l file","wc -c file","wc -w file","du -h file"],a:0,e:"-l은 줄 수, -w는 단어 수, -c는 바이트 수입니다."},
{n:35,s:1,q:"이전에 입력한 명령 목록을 확인하는 명령어는?",o:["history","last","who","jobs"],a:0,e:"!번호로 재실행할 수 있고, 기록은 ~/.bash_history에 저장됩니다. last는 로그인 이력을 봅니다."},

/* ---------------- 2과목 · 리눅스 활용 ---------------- */
{n:36,s:2,q:"CLI 환경에서 X 윈도를 수동으로 시작하는 명령은?",o:["startx","xinit -q","xhost +","xauth start"],a:0,e:"startx는 ~/.xinitrc를 참조해 X 서버와 클라이언트를 띄웁니다."},
{n:37,s:2,q:"특정 호스트가 로컬 X 서버에 접근하도록 허용하는 명령은?",o:["xhost +192.168.0.10","xauth list","export DISPLAY=:0","startx -- :1"],a:0,e:"xhost는 호스트 기반 접근 제어이고, xauth는 매직 쿠키 기반의 더 안전한 방식입니다."},
{n:38,s:2,q:"SSH 접속 시 원격 서버의 GUI 프로그램을 로컬 화면에 띄우려면 사용해야 하는 옵션은?",o:["ssh -X user@host","ssh -p user@host","ssh -L user@host","ssh -N user@host"],a:0,e:"-X는 X11 포워딩, -L은 로컬 포트 포워딩입니다."},
{n:39,s:2,q:"여러 네트워크 인터페이스를 논리적으로 묶어 대역폭 확장과 이중화를 구현하는 기술은?",o:["본딩(Bonding) / 티밍(Teaming)","브리지(Bridge)","VLAN","NAT"],a:0,e:"active-backup, balance-rr 등의 모드를 지정해 장애 대비나 부하 분산을 구성합니다."},
{n:40,s:2,q:"firewalld에서 인터페이스별 신뢰 수준을 나누어 규칙을 적용하는 단위는?",o:["존(Zone)","체인(Chain)","테이블(Table)","프로파일(Profile)"],a:0,e:"public, trusted, internal 같은 존에 서비스와 포트를 등록하며, firewall-cmd로 관리합니다."},
{n:41,s:2,q:"iptables의 기본 체인에 해당하지 않는 것은?",o:["INPUT","OUTPUT","FORWARD","REDIRECT"],a:3,e:"filter 테이블의 기본 체인은 INPUT, OUTPUT, FORWARD입니다. REDIRECT는 nat 테이블에서 쓰는 타깃입니다."},
{n:42,s:2,q:"프로세스와 파일에 보안 컨텍스트를 부여해 강제적 접근 통제를 수행하는 리눅스 보안 모듈은?",o:["SELinux","PAM","sudo","TCP Wrapper"],a:0,e:"getenforce로 상태를 보고 setenforce로 Enforcing/Permissive를 전환합니다. PAM은 인증 모듈 체계입니다."},
{n:43,s:2,q:"SSH 공개키 인증을 설정할 때 클라이언트의 공개키를 등록해야 하는 서버 측 파일은?",o:["~/.ssh/authorized_keys","~/.ssh/id_rsa","~/.ssh/known_hosts","/etc/ssh/sshd_config"],a:0,e:"클라이언트에서 ssh-keygen으로 키 쌍을 만들고 공개키를 서버의 authorized_keys에 추가합니다. 개인키는 절대 서버로 옮기지 않습니다."},
{n:44,s:2,q:"DHCP 서버로부터 IP 주소를 새로 할당받는 클라이언트 명령은?",o:["dhclient","dhcpd","ifup","route add"],a:0,e:"dhclient는 클라이언트, dhcpd는 서버 데몬입니다."},
{n:45,s:2,q:"리눅스에서 DNS 서버를 구축할 때 사용하는 대표적인 소프트웨어는?",o:["BIND(named)","Postfix","Squid","vsftpd"],a:0,e:"BIND의 데몬 이름이 named이며 /etc/named.conf와 존 파일로 설정합니다."},
{n:46,s:2,q:"웹 캐시와 프록시 서버 기능을 제공하는 소프트웨어는?",o:["Squid","Samba","Nagios","Zabbix"],a:0,e:"Squid는 캐싱으로 대역폭을 절약하고 접근 제어도 수행합니다."},
{n:47,s:2,q:"리눅스 커널에 내장된 하이퍼바이저 기반 가상화 기술은?",o:["KVM","Docker","LXC","Wine"],a:0,e:"KVM은 전가상화를 지원하는 커널 모듈이며 QEMU와 함께 사용합니다. Docker와 LXC는 컨테이너 방식입니다."},
{n:48,s:2,q:"실행 중인 도커 컨테이너 목록을 확인하는 명령은?",o:["docker ps","docker images","docker build","docker pull"],a:0,e:"docker ps -a는 정지된 컨테이너까지 보여 주고, docker images는 이미지 목록을 표시합니다."},
{n:49,s:2,q:"시스템 자원과 서비스 상태를 지속적으로 감시하고 장애를 알리는 오픈소스 모니터링 도구는?",o:["Nagios, Zabbix","Samba, NFS","Squid, Apache","dd, rsync"],a:0,e:"임계치를 넘으면 알림을 보내는 방식으로 운영됩니다."},
{n:50,s:2,q:"임베디드 리눅스가 활용되는 분야로 보기 어려운 것은?",o:["공유기·셋톱박스 같은 네트워크 장비","스마트 TV와 IoT 기기","산업용 제어 장비","윈도우 전용 게임 실행 환경"],a:3,e:"윈도우 전용 애플리케이션 실행은 Wine 같은 호환 계층의 영역이며 임베디드 리눅스의 활용 분야가 아닙니다."}
]});

EXAMS.push({title:"제3회 실전 모의고사",note:"실무 시나리오·헷갈리는 옵션 구분 · 고난도",q:[

/* ---------------- 1과목 · 리눅스 일반 ---------------- */
{n:1,s:1,q:"오픈소스 라이선스 중 소스 공개 의무가 가장 약해 상용 제품에 결합하기 쉬운 것은?",o:["GPL","LGPL","AGPL","BSD"],a:3,e:"BSD·MIT 계열은 저작권 표시만 유지하면 되는 허용적(permissive) 라이선스입니다. GPL은 강한 카피레프트, LGPL은 라이브러리 링크에 한해 완화, AGPL은 네트워크 제공까지 공개 의무를 확장합니다."},
{n:2,s:1,q:"리눅스 배포판과 패키지 관리자의 연결이 옳지 않은 것은?",o:["Ubuntu — apt / dpkg","Rocky Linux — dnf / rpm","openSUSE — zypper / rpm","Arch Linux — yum / rpm"],a:3,e:"Arch Linux는 pacman을 사용합니다."},
{n:3,s:1,q:"GRUB2의 설정을 변경한 뒤 실제 부팅 설정에 반영하기 위해 실행해야 하는 명령은?",o:["grub2-mkconfig -o /boot/grub2/grub.cfg","grub2-install /dev/sda1","update-initramfs -u","systemctl daemon-reload"],a:0,e:"/etc/default/grub을 고친 뒤 grub2-mkconfig(데비안 계열은 update-grub)로 grub.cfg를 다시 생성합니다."},
{n:4,s:1,q:"루트 비밀번호를 분실했을 때 복구를 위해 부팅하는 모드는?",o:["single user mode(rescue.target)","graphical.target","multi-user.target","reboot.target"],a:0,e:"GRUB에서 커널 파라미터에 single 또는 rd.break를 주어 단일 사용자 모드로 진입한 뒤 passwd로 변경합니다."},
{n:5,s:1,q:"현재 마운트된 파일 시스템의 목록과 옵션을 확인하는 방법으로 옳지 않은 것은?",o:["mount 명령을 인자 없이 실행","cat /etc/mtab","findmnt","cat /etc/fstab"],a:3,e:"/etc/fstab은 부팅 시 마운트할 목록을 정의한 설정 파일일 뿐, 현재 마운트 상태를 나타내지 않습니다."},
{n:6,s:1,q:"파일 시스템의 마운트 옵션 중 해당 영역에서 실행 파일의 실행을 막는 것은?",o:["noexec","nosuid","nodev","ro"],a:0,e:"nosuid는 SetUID 비트를 무시하고, nodev는 장치 파일을 인식하지 않으며, ro는 읽기 전용으로 마운트합니다."},
{n:7,s:1,q:"디스크 용량은 남아 있는데 파일을 만들 수 없다면 가장 먼저 의심할 것은?",o:["inode 고갈","스왑 부족","권한 문제","네트워크 지연"],a:0,e:"작은 파일이 대량으로 쌓이면 inode가 먼저 소진됩니다. df -i로 확인합니다."},
{n:8,s:1,q:"디렉터리별 디스크 사용량을 큰 순서로 확인하기에 가장 적절한 명령은?",o:["du -sh * | sort -hr","df -h","ls -al","free -m"],a:0,e:"du는 디렉터리 사용량을 계산하며 sort -hr로 사람이 읽는 단위 기준 내림차순 정렬을 합니다."},
{n:9,s:1,q:"umask가 002일 때 새로 생성되는 디렉터리의 기본 권한은?",o:["775","755","664","644"],a:0,e:"디렉터리 기본값 777에서 002를 빼면 775입니다. 일반 파일은 666에서 빼서 664가 됩니다."},
{n:10,s:1,q:"디렉터리에 SetGID를 설정했을 때의 효과로 옳은 것은?",o:["그 디렉터리에서 생성되는 파일이 디렉터리의 그룹을 상속받는다","소유자만 파일을 삭제할 수 있다","실행 시 소유자 권한으로 동작한다","하위 디렉터리 생성이 금지된다"],a:0,e:"협업 디렉터리에서 그룹을 통일할 때 사용합니다. 소유자만 삭제 가능하게 하는 것은 Sticky Bit입니다."},
{n:11,s:1,q:"프로세스가 열고 있는 파일과 네트워크 소켓을 확인하는 명령은?",o:["lsof","ps -ef","top","vmstat"],a:0,e:"lsof -i :80 처럼 특정 포트를 점유한 프로세스를 찾을 때도 유용합니다."},
{n:12,s:1,q:"터미널 연결이 끊겨도 실행 중인 명령이 종료되지 않게 하는 방법은?",o:["nohup 명령 &","명령 > /dev/null","kill -HUP","bg %1"],a:0,e:"nohup은 SIGHUP을 무시하게 합니다. screen이나 tmux 같은 터미널 멀티플렉서를 쓰기도 합니다."},
{n:13,s:1,q:"프로세스에 설정 파일을 다시 읽으라고 알리는 데 관례적으로 사용하는 시그널은?",o:["SIGHUP(1)","SIGKILL(9)","SIGTERM(15)","SIGSTOP(19)"],a:0,e:"많은 데몬이 SIGHUP을 받으면 재시작 없이 설정을 다시 읽습니다."},
{n:14,s:1,q:"SIGKILL(9)로도 종료되지 않는 프로세스의 상태는?",o:["D(uninterruptible sleep)","S(sleeping)","R(running)","T(stopped)"],a:0,e:"D 상태는 주로 I/O 완료를 기다리는 중이라 시그널로 깨울 수 없습니다. 원인이 되는 I/O나 스토리지를 살펴야 합니다."},
{n:15,s:1,q:"시스템 부하 평균(load average) 값이 4.0이고 CPU 코어가 2개일 때의 해석으로 옳은 것은?",o:["실행 대기가 쌓여 과부하 상태이다","여유가 충분한 상태이다","메모리가 부족하다는 뜻이다","디스크가 가득 찼다는 뜻이다"],a:0,e:"부하 평균이 코어 수를 넘으면 대기열이 쌓이고 있다는 신호입니다. uptime과 top에서 확인합니다."},
{n:16,s:1,q:"메모리 상태에서 buff/cache가 크게 잡혀 있을 때의 해석으로 옳은 것은?",o:["커널이 캐시로 활용 중이며 필요 시 회수되므로 대체로 문제가 아니다","메모리 누수가 발생한 것이다","즉시 재부팅해야 한다","스왑이 고갈된 것이다"],a:0,e:"free 출력의 available 값을 봐야 실제 가용 메모리를 알 수 있습니다."},
{n:17,s:1,q:"사용자를 생성하면서 홈 디렉터리를 만들고 로그인 셸을 지정하는 명령은?",o:["useradd -m -s /bin/bash kim","useradd -M -s /sbin/nologin kim","usermod -d /home/kim kim","adduser --no-create-home kim"],a:0,e:"-m은 홈 디렉터리 생성, -M은 생성 안 함, -s는 로그인 셸 지정입니다."},
{n:18,s:1,q:"서비스 계정처럼 로그인을 막아야 하는 사용자에게 지정하는 셸은?",o:["/sbin/nologin","/bin/bash","/bin/sh","/bin/csh"],a:0,e:"/sbin/nologin 또는 /bin/false를 지정하면 대화형 로그인이 차단됩니다."},
{n:19,s:1,q:"사용자를 기존 그룹에 추가하면서 기존 보조 그룹을 유지하려면 사용해야 하는 옵션은?",o:["usermod -aG dev kim","usermod -G dev kim","groupadd dev kim","gpasswd -d kim dev"],a:0,e:"-a 없이 -G만 쓰면 기존 보조 그룹이 모두 지워지고 지정한 그룹으로 대체됩니다."},
{n:20,s:1,q:"특정 사용자에게 재부팅 명령만 sudo로 허용하려 할 때 편집해야 하는 것은?",o:["visudo로 /etc/sudoers 편집","/etc/passwd 직접 수정","chmod u+s /sbin/reboot","/etc/group에 추가"],a:0,e:"visudo는 문법 검사를 수행하므로 sudoers 파일은 반드시 visudo로 편집합니다."},
{n:21,s:1,q:"rpm 명령으로 이미 설치된 패키지를 조회하는 옵션은?",o:["rpm -qa","rpm -ivh","rpm -e","rpm -Uvh"],a:0,e:"-q는 질의, -a는 전체입니다. -i 설치, -U 업그레이드, -e 삭제입니다."},
{n:22,s:1,q:"특정 파일이 어느 패키지에 속하는지 확인하는 명령은?",o:["rpm -qf /usr/bin/vim","rpm -ql vim","which vim","find / -name vim"],a:0,e:"-qf는 파일이 속한 패키지를, -ql은 패키지에 포함된 파일 목록을 보여 줍니다."},
{n:23,s:1,q:"tar 아카이브의 내용을 풀지 않고 목록만 확인하는 명령은?",o:["tar -tvf data.tar","tar -xvf data.tar","tar -cvf data.tar","tar -rvf data.tar"],a:0,e:"t는 list, x는 추출, c는 생성, r은 추가입니다."},
{n:24,s:1,q:"압축률이 일반적으로 가장 높은 압축 형식은?",o:["xz","gzip","compress","zip"],a:0,e:"압축률은 xz > bzip2 > gzip 순이며, 속도는 대체로 반대입니다."},
{n:25,s:1,q:"명령의 출력을 화면에 보여 주면서 동시에 파일로도 저장하는 명령은?",o:["tee","xargs","cat","script"],a:0,e:"cmd | tee out.log 형태로 사용하며, -a 옵션은 이어쓰기입니다."},
{n:26,s:1,q:"grep에서 패턴과 일치하지 않는 줄만 출력하는 옵션은?",o:["-v","-i","-c","-n"],a:0,e:"-v는 반전, -i는 대소문자 무시, -c는 개수, -n은 줄 번호입니다."},
{n:27,s:1,q:"find로 찾은 파일에 대해 명령을 직접 실행하는 옵션은?",o:["-exec","-print","-name","-type"],a:0,e:"find . -name '*.tmp' -exec rm {} \\; 형태로 사용하며, {}가 찾은 파일로 치환됩니다."},
{n:28,s:1,q:"7일보다 오래된 로그 파일을 찾는 조건으로 옳은 것은?",o:["find /var/log -mtime +7","find /var/log -mtime -7","find /var/log -size +7","find /var/log -atime 7"],a:0,e:"+7은 7일보다 이전, -7은 7일 이내를 뜻합니다."},
{n:29,s:1,q:"셸에서 명령 치환(command substitution)을 수행하는 표기는?",o:["$(command)","${variable}","[[ command ]]","(( command ))"],a:0,e:"$(...) 또는 백틱으로 명령 결과를 값으로 사용합니다. ${}는 변수 확장, (())는 산술 연산입니다."},
{n:30,s:1,q:"셸 스크립트에서 리스트를 순회하는 반복문 표기로 옳은 것은?",o:["for i in 1 2 3; do echo $i; done","for (i=1; i<=3; i++) echo $i","foreach i (1 2 3) echo $i","loop i in 1 2 3 { echo $i }"],a:0,e:"bash는 for ... in ...; do ... done 구조를 사용하며, C 스타일은 for ((i=0;i<3;i++))로 씁니다."},
{n:31,s:1,q:"변수에 값이 비어 있을 때 기본값을 사용하는 파라미터 확장 표기는?",o:["${VAR:-default}","${VAR:=default}의 반대","${#VAR}","${VAR/old/new}"],a:0,e:":-는 기본값을 반환만 하고, :=는 변수에 대입까지 합니다. ${#VAR}는 길이, ${VAR/old/new}는 치환입니다."},
{n:32,s:1,q:"환경 변수를 자식 프로세스에도 전달되도록 만드는 명령은?",o:["export","set","alias","unset"],a:0,e:"export VAR=value로 지정해야 하위 프로세스가 상속받습니다."},
{n:33,s:1,q:"시스템 전체 사용자에게 적용할 환경 변수를 설정하기에 적절한 파일은?",o:["/etc/profile","~/.bashrc","~/.bash_logout","/etc/hostname"],a:0,e:"/etc/profile 또는 /etc/profile.d/ 아래 스크립트를 사용합니다."},
{n:34,s:1,q:"시스템 시간을 NTP 서버와 동기화하는 서비스는?",o:["chronyd","crond","rsyslog","auditd"],a:0,e:"최근 배포판은 chronyd(또는 systemd-timesyncd)를 사용하며 timedatectl로 상태를 확인합니다."},
{n:35,s:1,q:"현재 시스템에 로그인한 사용자를 확인하는 명령은?",o:["who","last","history","id"],a:0,e:"who와 w는 현재 접속자, last는 로그인 이력, id는 사용자의 UID·GID를 보여 줍니다."},

/* ---------------- 2과목 · 리눅스 활용 ---------------- */
{n:36,s:2,q:"X 윈도 시스템의 최신 대체 디스플레이 서버 프로토콜은?",o:["Wayland","Metacity","Mutter","Compiz"],a:0,e:"Wayland는 X11의 복잡한 구조를 단순화한 프로토콜로 최근 배포판의 기본값이 되고 있습니다. 나머지는 윈도 매니저·컴포지터입니다."},
{n:37,s:2,q:"창의 이동·크기 조절·배치를 담당하는 X 윈도 구성 요소는?",o:["윈도 매니저","디스플레이 매니저","X 서버","X 클라이언트"],a:0,e:"디스플레이 매니저는 로그인 화면을, 윈도 매니저는 창 관리를 담당합니다."},
{n:38,s:2,q:"NetworkManager 환경에서 CLI로 네트워크 연결을 관리하는 명령은?",o:["nmcli","ifconfig","netstat","arp"],a:0,e:"nmcli connection show, nmcli device status 형태로 사용하며 nmtui는 텍스트 UI입니다."},
{n:39,s:2,q:"기본 게이트웨이를 포함한 라우팅 테이블을 확인하는 명령으로 옳은 것은?",o:["ip route show","ip addr show","ip link show","ip neigh show"],a:0,e:"ip addr은 주소, ip link는 인터페이스 상태, ip neigh는 ARP 캐시를 보여 줍니다."},
{n:40,s:2,q:"특정 포트가 열려 있는지 외부에서 점검할 때 사용할 수 있는 도구는?",o:["nmap","ping","dig","hostname"],a:0,e:"ping은 ICMP 응답만 확인하므로 포트 상태는 알 수 없습니다. nmap이나 telnet, nc로 확인합니다."},
{n:41,s:2,q:"DNS 레코드를 상세히 조회하는 명령으로 nslookup을 대체하는 것은?",o:["dig","host -a만 가능","whois","traceroute"],a:0,e:"dig @8.8.8.8 example.com MX 처럼 질의 서버와 레코드 타입을 지정할 수 있습니다."},
{n:42,s:2,q:"firewalld에서 변경한 규칙을 재부팅 후에도 유지하려면 필요한 옵션은?",o:["--permanent","--reload","--zone=public","--list-all"],a:0,e:"--permanent로 저장한 뒤 --reload로 적용해야 합니다. 옵션 없이 준 규칙은 런타임에만 유효합니다."},
{n:43,s:2,q:"Apache 웹 서버의 주 설정 파일 경로로 알맞은 것은?",o:["/etc/httpd/conf/httpd.conf","/etc/nginx/nginx.conf","/etc/samba/smb.conf","/etc/vsftpd/vsftpd.conf"],a:0,e:"레드햇 계열은 /etc/httpd, 데비안 계열은 /etc/apache2 아래에 설정이 있습니다."},
{n:44,s:2,q:"NFS 서버에서 공유할 디렉터리와 접근 권한을 정의하는 파일은?",o:["/etc/exports","/etc/fstab","/etc/samba/smb.conf","/etc/hosts.allow"],a:0,e:"/etc/exports에 정의한 뒤 exportfs -r로 적용합니다."},
{n:45,s:2,q:"Samba 서버의 설정 파일 문법을 검사하는 명령은?",o:["testparm","smbclient","smbpasswd","nmblookup"],a:0,e:"testparm은 smb.conf의 문법 오류를 점검합니다."},
{n:46,s:2,q:"메일 수신 프로토콜을 제공하여 클라이언트가 메일함을 읽게 해 주는 소프트웨어는?",o:["Dovecot","Postfix","Sendmail","Exim"],a:0,e:"Postfix·Sendmail·Exim은 메일을 보내는 MTA이고, Dovecot은 POP3·IMAP을 제공합니다."},
{n:47,s:2,q:"컨테이너와 가상 머신의 차이로 옳은 것은?",o:["컨테이너는 호스트 커널을 공유하고 가상 머신은 게스트 OS 커널을 따로 갖는다","컨테이너가 가상 머신보다 항상 격리 수준이 높다","가상 머신이 컨테이너보다 항상 시작이 빠르다","둘 다 하이퍼바이저가 필수이다"],a:0,e:"커널을 공유하는 만큼 컨테이너는 가볍고 빠르지만 격리 수준은 가상 머신보다 낮습니다."},
{n:48,s:2,q:"여러 컨테이너를 배포·확장·복구까지 자동으로 관리하는 오케스트레이션 도구는?",o:["Kubernetes","Vagrant","Ansible","Jenkins"],a:0,e:"Ansible은 구성 관리, Jenkins는 CI/CD, Vagrant는 개발용 가상 머신 관리 도구입니다."},
{n:49,s:2,q:"클라우드 컴퓨팅 서비스 유형 중, 서버와 스토리지 같은 인프라 자원을 제공하는 것은?",o:["IaaS","PaaS","SaaS","BaaS"],a:0,e:"IaaS는 인프라, PaaS는 개발 플랫폼, SaaS는 완성된 소프트웨어를 제공합니다."},
{n:50,s:2,q:"슈퍼컴퓨터 상위 목록에서 리눅스가 사실상 전부를 차지하는 이유로 보기 어려운 것은?",o:["소스 공개로 하드웨어에 맞춘 커널 최적화가 가능하다","라이선스 비용 부담이 없다","클러스터·병렬 처리 도구 생태계가 풍부하다","그래픽 사용자 인터페이스가 가장 화려하다"],a:3,e:"고성능 컴퓨팅 환경에서는 GUI가 거의 쓰이지 않으며 오히려 자원을 아끼기 위해 배제합니다."}
]});
